	;          Object		Mappings	Subtype Frame Arttile
	dbglistobj Obj_Ring,		Map_Ring,	   0,   0, make_art_tile(ArtTile_Ring,1,1)
	dbglistobj Obj_Monitor,			Map_Monitor,		       0,   0, make_art_tile(ArtTile_Monitors,0,0)
	dbglistobj Obj_Monitor,			Map_Monitor,		       1,   2, make_art_tile(ArtTile_Monitors,0,0)
	dbglistobj Obj_Monitor,			Map_Monitor,		       2,   3, make_art_tile(ArtTile_Monitors,0,0)
	dbglistobj Obj_Monitor,			Map_Monitor,		       3,   4, make_art_tile(ArtTile_Monitors,0,0)
	dbglistobj Obj_Monitor,			Map_Monitor,		       4,   5, make_art_tile(ArtTile_Monitors,0,0)
	dbglistobj Obj_Monitor,			Map_Monitor,		       5,   6, make_art_tile(ArtTile_Monitors,0,0)
	dbglistobj Obj_Monitor,			Map_Monitor,		       6,   7, make_art_tile(ArtTile_Monitors,0,0)
	dbglistobj Obj_Monitor,			Map_Monitor,		       7,   8, make_art_tile(ArtTile_Monitors,0,0)
	dbglistobj Obj_Monitor,			Map_Monitor,		       8,   9, make_art_tile(ArtTile_Monitors,0,0)
    dbglistobj Obj_Monitor,         Map_Monitor,               9,   $A,make_art_tile(ArtTile_Monitors,0,0)
    dbglistobj Obj_Monitor,         Map_Monitor,               $A,  $B,make_art_tile(ArtTile_Monitors,0,0)
	dbglistobj Obj_PathSwap,	Map_PathSwap,	   9,   1, make_art_tile(ArtTile_Ring,1,0)
	dbglistobj Obj_PathSwap,	Map_PathSwap,	  $D,   5, make_art_tile(ArtTile_Ring,1,0)
	dbglistobj Obj_Spring,		Map_Spring,	 $81,   0, make_art_tile($4A4,0,0)
	dbglistobj Obj_Spring,		Map_Spring,	 $90,   3, make_art_tile($4B4,0,0)
	dbglistobj Obj_Spring,		Map_Spring,	 $A0,   6, make_art_tile($4A4,0,0)
	dbglistobj Obj_Spikes,		Map_Spikes,	   0,   0, make_art_tile($49C,0,0)
